markdown: kramdown
kramdown:
  input: GFM
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: false #true
  syntax_highlighter:  rouge
  syntax_highlighter_opts:
    #default_lang: c
    css_class: 'highlight'
    #line_numbers: true
    #start_line: 1
    #inline_theme: colorful
    wrap: true
  #coderay:
   # coderay_line_numbers:  nil #inline  #nil
   # coderay_wrap: div  # div
   # coderay_tab_width: 4
   # coderay_bold_every: 10
   # coderay_css: class
#highlighter: rouge
permalink: /:categories/:title.html
url: "wdyggh.github.io"
lsi: false
####pygments: true
safe: false
#auto: false 

paginate: 10
paginate_path: "page:num"

# presonal config
domain: wdyggh.github.io
title: wdyggh's Blog
description: Python, Linux, embedded, FPGA   ...
author: wdy
email: wdyggh@gmail.com
github: wdyggh

config:
  js_dir:
  img_dir:
  css_dir:

baseurl: ""
# Gems
gems: 
  - jekyll-paginate

# personal ID
addson_config:
  analytics:
    google:
      tracking_id: 'UA-91781695-1'
  adsense:
    google:
      client_id: 'ca-pub-7553071169021268'
  comment:
    disqus:
      shortname : 'httpwdygghgithubioindexhtml'
