# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: false #true
  #enable_coderay: false
  syntax_highlighter:  rouge
  #coderay:
   # coderay_line_numbers:  nil #inline  #nil
   # coderay_wrap: div  # div
   # coderay_tab_width: 4
   # coderay_bold_every: 10
   # coderay_css: class
#highlighter: rouge
permalink: /:categories/:title.html
url: "http://wdyggh.github.io"
lsi: false
####pygments: true
safe: false
#auto: false 

paginate: 10
paginate_path: "page:num"

# presonal config
domain: wdyggh.github.io
title: wdyggh's Blog
description: c, avr, embedded, Linux, python ...
author: wdy
email: wdyggh@gmail.com
github: wdyggh

config:
  js_dir:
  img_dir:
  css_dir:
