# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  inline  #nil
    coderay_wrap: span  # div
#highlighter: rouge
permalink: /:categories/:title.html
url: "http://wdyggh.github.io"
lsi: false
#pygments: true
safe: false
auto: false 

paginate: 10
paginate_path: "page:num"

# presonal config
domain: wdyggh.github.io
title: wdyggh's Blog
description: c, avr, embedded, Linux, python ...
author: wdy
email: wdyggh@gmail.com
github: wdyggh

config:
  js_dir:
  img_dir:
  css_dir:
